1.Extract data from the givenSalaryGender CSV fileand store the data from each column in a separate NumPy array.

In [5]:
import numpy as np

# Load data from the CSV file
file_path = r"/Users/aksavxavier/Desktop/SalaryGender_3b3js.csv"  
data = np.genfromtxt(file_path, delimiter=',', names=True, dtype=None)

# Extract data from each column
salary = data['Salary']
gender = data['Gender']
age = data['Age']
phd = data['PhD']

# Print the extracted data
print("Salary array:")
print(salary)

print("\nGender array:")
print(gender)

print("\nAge array:")
print(age)

print("\nPhD array:")
print(phd);


Salary array:
[140.    30.    35.1   30.    80.    30.    60.    31.1  125.    51.
   3.    46.   150.     3.   130.    15.   130.    84.   190.    74.
  73.    10.    50.     7.     9.5   15.2   28.6   20.    72.    81.
 100.    90.    90.    35.    30.    25.    52.     9.    63.    72.
  16.    92.   106.     2.5    9.    32.    32.    55.    52.    28.
  20.    14.7   22.3   34.8   84.    19.   160.    65.    55.     4.6
 102.    20.    62.    55.    45.6   40.    24.    35.    48.    20.
  40.7   15.     0.25 152.    39.8   12.    30.   120.     1.7   36.
  96.    38.    90.     9.    25.8   22.    38.8   72.    89.    41.
  89.    25.    52.   115.    66.    18.6  152.     1.8   35.     4.  ]

Gender array:
[1 0 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1
 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0]

Age array:
[47 65 56 23 53 27 53 30 44 63 22 59 60 28 65 25 65 47 66 45 

2.Find:
1. The number of men with a Ph.D.
2. The number of women with a Ph.D.

In [8]:
import numpy as np

# Load data from the CSV file
file_path =r"/Users/aksavxavier/Desktop/SalaryGender_3b3js.csv"
data = np.genfromtxt(file_path, delimiter=',', names=True, dtype=None)

# Extract 'Gender' and 'PhD' columns
gender = data['Gender']
phd = data['PhD']

# Find the number of men with a Ph.D.
men_with_phd = np.sum((gender == b'M') & (phd == 1))

# Find the number of women with a Ph.D.
women_with_phd = np.sum((gender == b'F') & (phd == 1))

# Print the results
print("Number of men with a Ph.D.:", men_with_phd)
print("Number of women with a Ph.D.:", women_with_phd)


Number of men with a Ph.D.: 0
Number of women with a Ph.D.: 0


/var/folders/xd/j94637p953s5wh10jyypd0j00000gn/T/ipykernel_17527/2448268619.py:12: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  men_with_phd = np.sum((gender == b'M') & (phd == 1))
/var/folders/xd/j94637p953s5wh10jyypd0j00000gn/T/ipykernel_17527/2448268619.py:15: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  women_with_phd = np.sum((gender == b'F') & (phd == 1))


3.Store the "Age"and "Ph.D."columns in one DataFrame and delete the data of all people who don't have a Ph.D.from the SalaryGender CSV file

In [10]:
import pandas as pd
import numpy as np

# Load data from the CSV file into a DataFrame
file_path = r"/Users/aksavxavier/Desktop/SalaryGender_3b3js.csv"
df = pd.read_csv(file_path)

# Filter out rows where individuals don't have a Ph.D.
df_with_phd = df[df['PhD'] == 1]

# Select and display the "Age" and "Ph.D." columns
selected_columns = df_with_phd[['Age', 'PhD']]
print(selected_columns)


    Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1


5.Calculate the total number of people who have a Ph.D.degree from the SalaryGender CSV file.

In [11]:
import pandas as pd

# Load data from the CSV file into a DataFrame
file_path = r"/Users/aksavxavier/Desktop/SalaryGender_3b3js.csv" 
df = pd.read_csv(file_path)

# Count the number of people with a Ph.D.
total_phd_count = df[df['PhD'] == 1].shape[0]

# Print the result
print("Total number of people with a Ph.D. degree:", total_phd_count)


Total number of people with a Ph.D. degree: 39


6.How  do  you count the frequency  ofeach  value  appearingin the  givenarray  of integers?[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]Answer:array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1]) which means 0 comes 4 times, 1 comes 2 times, 2 comes 1 time, 3 comes 1 time and so on.

In [12]:
import numpy as np

# Given array
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])

# Count the frequency of each value
values, counts = np.unique(arr, return_counts=True)

# Create a new array representing the frequency of each value
result = np.zeros(np.max(arr) + 1, dtype=int)
result[values] = counts

print(result)


[4 2 1 1 3 2 0 0 0 1]


6.Create a NumPyarray [[0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9,10, 11]]) and filter the elements greater than 5

In [13]:
import numpy as np

# Create a NumPy array
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]])

# Filter elements greater than 5
filtered_elements = arr[arr > 5]

print("Original array:")
print(arr)

print("\nFiltered elements greater than 5:")
print(filtered_elements)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Filtered elements greater than 5:
[ 6  7  8  9 10 11]


7.Create a NumPy array having NaN (Not a Number) and print it.array([ nan,   1.,   2.,  NaN,   3.,   4.,   5.]
Print the same array omitting all elements,which are NaN.

In [15]:
import numpy as np

# Create a NumPy array with NaN values
my_array = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])

# Omit NaN elements
array_without_nan = my_array[~np.isnan(my_array)]

# Print the array without NaN elements
print(array_without_nan)


[1. 2. 3. 4. 5.]


8.Create  a  10x10  array  with  random  values  and  find  the  minimum  and  maximum values.

In [16]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

# Print the array and the minimum and maximum values
print("Random Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:
[[0.10044456 0.37177933 0.48716443 0.58707046 0.87516386 0.62932209
  0.242637   0.05715189 0.793856   0.50882521]
 [0.84984382 0.60836747 0.0383905  0.91541087 0.28648159 0.39415631
  0.40850493 0.1674138  0.00958766 0.33665836]
 [0.61339143 0.72565677 0.48648675 0.9944583  0.61027943 0.80404215
  0.9330414  0.44190168 0.24294202 0.75053883]
 [0.50430952 0.02298165 0.38804722 0.32366574 0.04151786 0.37695886
  0.20266814 0.43045283 0.37373937 0.81891006]
 [0.73335995 0.49348991 0.77820985 0.63720733 0.37016489 0.91375146
  0.43186398 0.44433259 0.86772977 0.00112517]
 [0.94612239 0.47686093 0.8304463  0.10587907 0.18054444 0.40836027
  0.53497334 0.14956195 0.34639731 0.96300994]
 [0.3960893  0.02789228 0.599034   0.11226171 0.39219156 0.75333665
  0.46667765 0.91688354 0.7155584  0.95770228]
 [0.16354263 0.02188221 0.13553119 0.09474906 0.29185906 0.83143055
  0.37491352 0.20407789 0.44334233 0.29122092]
 [0.16154025 0.71977089 0.35640563 0.66680406 0.75560387 0.9974652

9.Create a random vector of size 30 and find the mean value.

In [17]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Find the mean value
mean_value = np.mean(random_vector)

# Print the random vector and the mean value
print("Random Vector:")
print(random_vector)
print("\nMean Value:", mean_value)


Random Vector:
[0.25674772 0.40365799 0.87436274 0.42879394 0.8532181  0.01144819
 0.99202412 0.68652249 0.39406503 0.98174599 0.72291511 0.91159466
 0.68233907 0.09224549 0.82563739 0.63599531 0.67902659 0.75137282
 0.39522985 0.81022406 0.20398938 0.94335348 0.68195097 0.72218062
 0.39057876 0.35389678 0.22154171 0.56292892 0.76561332 0.72456708]

Mean Value: 0.5986589222678264


10.Create a NumPyarray  having  elements  0  to  10  And  negate  all  the  elements between 3 and 9.

In [18]:
import numpy as np

# Create a NumPy array with elements 0 to 10
my_array = np.arange(11)

# Negate elements between 3 and 9
my_array[(my_array >= 3) & (my_array <= 9)] *= -1

# Print the modified array
print(my_array)


[ 0  1  2 -3 -4 -5 -6 -7 -8 -9 10]


11.Create a random array of 3 rows and 3 columns and sort it according to the first, second,or third column.

In [19]:
import numpy as np

# Create a random array of 3x3
random_array = np.random.rand(3, 3)

# Print the original array
print("Original Array:")
print(random_array)

# Sort based on the first column
sorted_array_first_col = random_array[random_array[:, 0].argsort()]
print("\nSorted by the first column:")
print(sorted_array_first_col)

# Sort based on the second column
sorted_array_second_col = random_array[random_array[:, 1].argsort()]
print("\nSorted by the second column:")
print(sorted_array_second_col)

# Sort based on the third column
sorted_array_third_col = random_array[random_array[:, 2].argsort()]
print("\nSorted by the third column:")
print(sorted_array_third_col)


Original Array:
[[0.0502277  0.29192561 0.91103763]
 [0.30987765 0.83395648 0.47804929]
 [0.76492947 0.33785727 0.859575  ]]

Sorted by the first column:
[[0.0502277  0.29192561 0.91103763]
 [0.30987765 0.83395648 0.47804929]
 [0.76492947 0.33785727 0.859575  ]]

Sorted by the second column:
[[0.0502277  0.29192561 0.91103763]
 [0.76492947 0.33785727 0.859575  ]
 [0.30987765 0.83395648 0.47804929]]

Sorted by the third column:
[[0.30987765 0.83395648 0.47804929]
 [0.76492947 0.33785727 0.859575  ]
 [0.0502277  0.29192561 0.91103763]]


12.Create a four dimensions arraytogetthesum over the last two axes at once.

In [21]:
import numpy as np

# Create a 4D array (3x3x3x3)
four_dimensions_array = np.random.rand(3, 3, 3, 3)

# Print the original array
print("Original 4D Array:")
print(four_dimensions_array)

# Calculate the sum over the last two axes at once
sum_last_two_axes = np.sum(four_dimensions_array, axis=(-2, -1))

# Print the result
print("\nSum over the last two axes at once:")
print(sum_last_two_axes)


Original 4D Array:
[[[[0.31235119 0.33904325 0.10907965]
   [0.47641954 0.65030866 0.34411788]
   [0.38829603 0.2717021  0.61723637]]

  [[0.13029551 0.00147652 0.51521796]
   [0.61597157 0.62252922 0.35874101]
   [0.97413819 0.83115454 0.82140025]]

  [[0.36119198 0.49336039 0.36951153]
   [0.0945636  0.07308761 0.79978506]
   [0.57928715 0.55455549 0.76095926]]]


 [[[0.40399696 0.79401698 0.13724302]
   [0.69702943 0.57050152 0.9074945 ]
   [0.98046257 0.23795704 0.51246468]]

  [[0.22033375 0.53537089 0.75934246]
   [0.56885736 0.94344241 0.39226933]
   [0.5100279  0.22108054 0.94504524]]

  [[0.42938999 0.1293856  0.10367195]
   [0.14108475 0.92983536 0.54163603]
   [0.81594264 0.18903738 0.40349333]]]


 [[[0.34910243 0.37852155 0.11605783]
   [0.10438546 0.56739463 0.40798925]
   [0.49183317 0.22672384 0.75167559]]

  [[0.91486276 0.14405868 0.47605345]
   [0.90698906 0.37464709 0.46986964]
   [0.66240125 0.91829732 0.01215603]]

  [[0.17531107 0.2868099  0.92177808]
   [0.01886

13.Create a random array and swap two rows of an array.

In [23]:
import numpy as np

# Create a random array (4x4 for example)
random_array = np.random.rand(4, 4)

# Print the original array
print("Original Array:")
print(random_array)

# Choose two rows to swap (e.g., row 1 and row 3)
row_to_swap1 = 1
row_to_swap2 = 3

# Swap the rows
random_array[[row_to_swap1, row_to_swap2], :] = random_array[[row_to_swap2, row_to_swap1], :]

# Print the array after swapping rows
print("\nArray after swapping rows:")
print(random_array)


Original Array:
[[0.48330356 0.84663732 0.74016219 0.95863498]
 [0.01283555 0.10441948 0.10446509 0.37300182]
 [0.57325292 0.02898498 0.53173046 0.04313106]
 [0.68983895 0.74254967 0.3839286  0.70853258]]

Array after swapping rows:
[[0.48330356 0.84663732 0.74016219 0.95863498]
 [0.68983895 0.74254967 0.3839286  0.70853258]
 [0.57325292 0.02898498 0.53173046 0.04313106]
 [0.01283555 0.10441948 0.10446509 0.37300182]]


In [ ]:
14.Create a random matrix and compute the matrix rank.

In [24]:
import numpy as np

# Create a random matrix (4x4 for example)
random_matrix = np.random.rand(4, 4)

# Print the original matrix
print("Original Matrix:")
print(random_matrix)

# Compute the matrix rank
matrix_rank = np.linalg.matrix_rank(random_matrix)

# Print the matrix rank
print("\nMatrix Rank:", matrix_rank)


Original Matrix:
[[0.76506974 0.92863818 0.57259049 0.69919488]
 [0.59809332 0.42881199 0.34949616 0.21632574]
 [0.62387747 0.4925419  0.79807877 0.59541567]
 [0.59460981 0.35601425 0.63785995 0.57209803]]

Matrix Rank: 4
