1.Convertthegivenlistintoa numpyarrayandreplacetheoddelementswith-2.Lst=[[1,2,3], [4,5,6], [7,8,9]]

In [1]:
import numpy as np

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Convert the list to a NumPy array
arr = np.array(lst)

# Replace the odd elements with -2
arr[arr % 2 != 0] = -2

print(arr)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


2.In the numpy array given below print all the elements ranging from 8 to 15.arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7])

# Use boolean indexing to get elements in the range [8, 15]
result = arr[(arr >= 8) & (arr <= 15)]

print(result)


[ 8  9 10 12]


3.Create a 3*3 n array thatincludes numbersfrom 1 to 9 and swap columns1 and 2.

In [3]:
import numpy as np

# Create a 3x3 array with numbers from 1 to 9
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original array:")
print(arr)

# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]

print("\nArray after swapping columns 1 and 2:")
print(arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping columns 1 and 2:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


4.In the given numpyarray replace the NaN values with the average of columnsarr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])

In [4]:
import numpy as np

arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the column-wise average, ignoring NaN values
column_averages = np.nanmean(arr, axis=0)

# Find the indices of NaN values
nan_indices = np.isnan(arr)

# Replace NaN values with column averages
arr[nan_indices] = np.take(column_averages, np.where(nan_indices)[1])

print("Array after replacing NaN with column averages:")
print(arr)


Array after replacing NaN with column averages:
[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


5.For the numpy array given below perform the following operation:i.Convert the numpy array into a numpymatrixii.Sort the values in a matrixarr = [[2,4,6],[1,3,5]]


In [6]:
import numpy as np

arr = np.array([[2, 4, 6],
                [1, 3, 5]])

# i. Convert the NumPy array into a NumPy matrix
matrix = np.matrix(arr)

# ii. Sort the values in the matrix
sorted_matrix = np.sort(matrix, axis=None)

print("Original NumPy array:")
print(arr)

print("\nNumPy matrix:")
print(matrix)

print("\nSorted values in the matrix:")
print(sorted_matrix)


Original NumPy array:
[[2 4 6]
 [1 3 5]]

NumPy matrix:
[[2 4 6]
 [1 3 5]]

Sorted values in the matrix:
[[1 2 3 4 5 6]]
